import { AppSidebar } from "@/components/app-sidebar";
import DashboardBreadCrumb from "@/components/dashboard-breadcrumb";
import { Separator } from "@/components/ui/separator";

import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { Space_Grotesk } from "next/font/google";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'], // Specify the necessary subsets
  variable: '--font-space-grotesk', // Optional: Define a CSS variable for use with Tailwind CSS
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <div className={`${spaceGrotesk.variable} flex flex-col w-full h-screen overflow-y-hidden`}>
          <header className="flex z-[100] h-16 shrink-0 items-center gap-2 border-b px-4 bg-accent/5">
            <div className="flex w-full items-center">
              <SidebarTrigger className="-ml-1" />
              <Separator orientation="vertical" className="mr-2 h-4" />
              <DashboardBreadCrumb />
            </div>
          </header>
          <div className="flex-1 overflow-y-auto">{children}</div>
        </div>
      </SidebarInset>
    </SidebarProvider>
  );
}
